### ISSUE TITLE
Wrong user visible text in the body of the cloned ticket

### ISSUE THREAD

**Issue by aureamunoz** [snowdrop-bot/snowdrop-bot#151]
While the link is correct, its user-visible text is not --> https://github.com/snowdrop-zen/quarkus-operator-sdk/issues/5

**Comment by aureamunoz** [comment]
the text `$upstream:17$` is added to the downstream issue when it's cloned in order to be able to find and match it with the upstream one. So this is not an error. The link to the upsream issue is added a few lines above. So I close this issue

**Comment by metacosm** [comment]
I wasn't talking about this, I was talking about: `quarkiverse#17`, which is wrong. It should be `quarkiverse/quarkus-operator-sdk#17`.

**Comment by aureamunoz** [comment]
Mmmmm, Ok. This is because the downstream issue is a clon of a [pull request upstream](https://github.com/quarkiverse/quarkus-operator-sdk/pull/17), so the link points to that pull request and not to the issue itself. GitHub's REST API v3 considers every pull request an issue. For this reason, "Issues" endpoints may return both issues and pull requests in the response and we are clonning them and creating an issue downstream. We need to think about how we can manage these cases @metacosm

**Comment by aureamunoz** [comment]
Ok, I think we should limit the clonation to the actual issues, not the pull requests. In this case the [issue concerned](https://github.com/java-operator-sdk/java-operator-sdk/issues/337) by the pull request has been cloned downstream --> https://github.com/snowdrop-zen/java-operator-sdk/issues/1. The clonation of the pull request doesn't add a lot of information, IMO, it just get us confused. WDYT @metacosm , @jacobdotcosta ? If you aggree I will implement this behaviour asap.

**Comment by jacobdotcosta** [comment]
IMO think we should keep cloning the PR as they are showing up in the report, even though if they show up as issues.

**Comment by aureamunoz** [comment]
It seems to work correctly like this.
