### ISSUE TITLE
Put in place Continuous Integration to test and build the container image

### ISSUE THREAD

**Issue by aureamunoz** [snowdrop-bot/snowdrop-bot#161]
We need to set up the Continuous integration in order to automate the building and testing the snowdrop-bot code at every commit.

- [ ] Create a github workflow containing a job for building the code. (look https://github.com/snowdrop/issues-manager/blob/b7da43bab1c7190e81ddab99240c9cbdfb74172d/.github/workflows/mvn-build.yml)  
- [ ] Deprecate the [ansible tasks](https://github.com/snowdrop/k8s-infra/tree/master/snowdrop-bot) to build/deploy the image as that will be automated by the Github workflow actions

**Comment by cmoulliard** [comment]
Can you please detail what it should be done (= TODO, tasks) within the description section please as this title tells what we would like to use CI but for doing what exactly ? @aureamunoz

**Comment by cmoulliard** [comment]
As this project contains a circleci job definition, I will then replace it with what we did for the project release-manager. Make sense ? 
Is the process to create the snowdrop-bot container image the only thing to be done ? 
Do we have a helm chart of yaml files to deploy/redeploy snowdrop-bot on the Hetzner K8s cluster ?

WDYT: @aureamunoz

**Comment by aureamunoz** [comment]
Closed via #163
