### ISSUE TITLE
Create Quay.io username & robotname github secrets

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop-bot/snowdrop-bot#162]
## TODO

As I cannot add github secrets, can you please create  @iocanel the following `github secrets` using password snwosrop store :

- `pass quay.io/snowdrop/username` -> `QUAY_USERNAME`
- `pass quay.io/snowdrop/robotname` -> `QUAY_ROBOT_NAME`

FYI: @aureamunoz @jacobdotcosta

**Comment by iocanel** [comment]
`QUAY_USERNAME` and `QUAY_ROBOT_TOKEN` have been created. 
The issue mentioned `QUARY_ROBOT_NAME` instead but I think that token was actually intended.
