### ISSUE TITLE
Error during deploy with helm chart

### ISSUE THREAD

**Issue by aureamunoz** [snowdrop-bot/snowdrop-bot#176]
When running the following command in order to deploy the Bot using the helm charts created under the folder `./deploy/charts`
```
helm install snowdrop-bot -n bot ./charts -f my-values.yml
```
I'm getting the following error: 
```
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1"
```

**Comment by aureamunoz** [comment]
It seems that this error is because of the k8s version. In the k8s instance where I'm trying to deploy the bot we have:
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.9", GitCommit:"500f5aba80d71253cc01ac6a8622b8377f4a7ef9", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:04Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
and it seems that v1 is only available on v19+. See https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122

So, can we update the hetzner k8s cluster, @cmoulliard ?

**Comment by cmoulliard** [comment]
Remarks:
- This is not a good idea to deploy the helm chart on a production machine
- As the application has been deployed, it must be first removed and next re-deployed

**Comment by cmoulliard** [comment]
> So, can we update the hetzner k8s cluster, @cmoulliard ?

A ticket has been created to upgrade it: https://github.com/snowdrop/k8s-infra/issues/177

**Comment by cmoulliard** [comment]
> and it seems that v1 is only available on v19+. See https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122

Can you propose a PR (that you will test locally using kind - 1.14 and 1.19) with this check - https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/templates/jenkins-controller-ingress.yaml#L1-L9 ?

@aureamunoz

**Comment by aureamunoz** [comment]
> Remarks:
> 
>     * This is not a good idea to deploy the helm chart on a production machine
> 
>     * As the application has been deployed, it must be first removed and next re-deployed

Ok, a note should be added to the doc.

**Comment by cmoulliard** [comment]
> Ok, a note should be added to the doc.

Why do you request to add a note as the current doc dont even mention that snowdrop-bot is deployed on our Hetzner k8s cluster ? @aureamunoz

**Comment by aureamunoz** [comment]
The cluster migration is planned for the next weeks: https://github.com/snowdrop/k8s-infra/issues/177
We can stop tests, the current helm chart work for `v1.20`
