### ISSUE TITLE
[Requirement] Populate team associate weekly report

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop-bot/snowdrop-bot#50]
## Request feature

Review and improve the way that Snowdrop bot populates the associate weekly report file according to the following requirements

- Every week a markdown or asciidoctor file should be created for the team using as file naming convention: `mmm-dd-yyyy-snowdrop-report.[md|adoc]`where `dd` corresponds to Thursday week date
- The report should start with title `Snowdrop Weekly report: mmm-dd-yyyy`
- Next, a section containing an empty table should be added with the following headers:
  - Item : counter increasing from `0001` .... `0099` and hyperlink to a github issue when it exists
  - Description: text
  - Who : assignee to a team associate
  -  Status
  **Remark**: The empty table will be filled by the manager when weekly report file reviewed and updated. If a better solution, then we could discuss it.
- Add a horizontal line
- Add a title - h2 for every associate
- Append as list the tasks and subtasks accomplished during the period last weekly report +1 day to current day
  ** Remark**:
  - Add the hyperlink of the PR or the github issue within the text reported
  - Organize the tasks/subtasks per project and epics
 - Include also tasks related to : community engagement, client support, ... using group `misc` and categories (to be discussed and could be changed)
    - Community engagement
    - Productization
    - Customer support
    - ....
 - Report the task using the following convention:
    - `test describing the task` - `hyperlink`
    - hyperlink should be included using its URL

Example of report generated

```
# Snowdrop weekly report: 19 Apr 2020

## Action Items

| Item | Description | Who | Status |
| ----- | -------- | ----- | ----- |
| 001 | ADD ME | ASSIGNE ME | DEFINE ME |

---

## Gytis Trikleris

 - Spring on Quarkus
   - Code Panache REST client - <https://github.com/cmoulliard/weekly-report/issues/1>

## Georgios Andrianakis

- Spring on Quarkus
    - Test related fixes
        - Make beans injected with @InjectMock unremoveable - <https://github.com/quarkusio/quarkus/pull/8491>
        - Allow the use of @QuarkusTestResource with QuarkusProdModeTest - <https://github.com/quarkusio/quarkus/pull/8597>

- RELEASE SB 2.2.6
    - Help Antonio and Auri
    - Help team with CVE + JIRA handling
- Misc
    - PR Reviews
    - Community engagement
``` 

**Last Remark**: This weekly report file for the team could also be populated as one file / associate in order to be used with the 1-1 meeting. To be discussed

WDYT @metacosm @gytis @iocanel

**Comment by metacosm** [comment]
>     * Every week a markdown or asciidoctor file should be created for the team using as file naming convention: `mmm-dd-yyyy-snowdrop-report.[md|adoc]`where `dd` corresponds to Thursday week date

Why? Couldn't this be an issue instead?

>     * Next, a section containing an empty table should be added with the following headers:
>       
>       * Item : counter increasing from `0001` .... `0099` and hyperlink to a github issue when it exists
>       * Description: text
>       * Who : assignee to a team associate
>       * Status
>         **Remark**: The empty table will be filled by the manager when weekly report file reviewed and updated. If a better solution, then we could discuss it.

Why a table and not linked issues? Each action item should lead to an issue to be closed so that it can be tracked.

>      * Add a horizontal line

Why?

>     * Add a title - h2 for every associate

Why a title? Why h2?

> 
>     * Append as list the tasks and subtasks accomplished during the period last weekly report +1 day to current day
>       ** Remark**:
>       
>       * Add the hyperlink of the PR or the github issue within the text reported
>       * Organize the tasks/subtasks per project and epics
> 
>     * Include also tasks related to : community engagement, client support, ... using group `misc` and categories (to be discussed and could be changed)
>       
>       * Community engagement
>       * Productization
>       * Customer support
>       * ....
> 
>     * Report the task using the following convention:
>       
>       * `test describing the task` - `hyperlink`
>       * hyperlink should be included using its URL
> 
> 
> Example of report generated
> 
> ```
> # Snowdrop weekly report: 19 Apr 2020
> 
> ## Action Items
> 
> | Item | Description | Who | Status |
> | ----- | -------- | ----- | ----- |
> | 001 | ADD ME | ASSIGNE ME | DEFINE ME |
> 
> ---
> 
> ## Gytis Trikleris
> 
>  - Spring on Quarkus
>    - Code Panache REST client - <https://github.com/cmoulliard/weekly-report/issues/1>
> 
> ## Georgios Andrianakis
> 
> - Spring on Quarkus
>     - Test related fixes
>         - Make beans injected with @InjectMock unremoveable - <https://github.com/quarkusio/quarkus/pull/8491>
>         - Allow the use of @QuarkusTestResource with QuarkusProdModeTest - <https://github.com/quarkusio/quarkus/pull/8597>
> 
> - RELEASE SB 2.2.6
>     - Help Antonio and Auri
>     - Help team with CVE + JIRA handling
> - Misc
>     - PR Reviews
>     - Community engagement
> ```
> 
> **Last Remark**: This weekly report file for the team could also be populated as one file / associate in order to be used with the 1-1 meeting. To be discussed
> 
> WDYT @metacosm @gytis @iocanel

My opinion is that the level of information captured here is wrong. It doesn't state purpose just format, which prescribes an implementation without helping figure out possibly better solutions. A more helpful description would state: I need this information because… instead of specifying how it might be formatted.

**Comment by cmoulliard** [comment]
> Why? Couldn't this be an issue instead?

If the report generated could be included within the description, then I'm fine to use a github issue as we could comment/discuss it as we do with normal github issue

**Comment by cmoulliard** [comment]
> Why a table and not linked issues? Each action item should lead to an issue to be closed so that it can be tracked.

I'm not sure that we need a ticket for every action as some actions could be related to by example: setup a meeting, send an email, contact x to request to do y, .... 

The table should not be generated by the reporting tool but will be used instead by myself to summarize the actions.

**Comment by cmoulliard** [comment]
> Why?

It's prettier ;-)

**Comment by cmoulliard** [comment]
> Why a title? Why h2?

To better organize/group the content of the report -> see example

**Comment by cmoulliard** [comment]
> My opinion is that the level of information captured here is wrong. It doesn't state purpose just format, which prescribes an implementation without helping figure out possibly better solutions. A more helpful description would state: I need this information because… instead of specifying how it might be formatted.

I think that you have not read correctly the description as it describes what I explect to get. So I will **again** repeat what is described :up:

```
Append as list the tasks and subtasks accomplished during the period last weekly report +1 day to current day
Add the hyperlink of the PR or the github issue within the text reported
Organize the tasks/subtasks per project and epics
Include also tasks related to : community engagement, client support, ... using group misc and categories (to be discussed and could be changed)
Community engagement
Productization
Customer support
....
Report the task using the following convention:
test describing the task - hyperlink
hyperlink should be included using its URL
```

**Comment by iocanel** [comment]
I think we can close this now
