### ISSUE TITLE
Add JIRA support to the bot

### ISSUE THREAD

**Issue by iocanel** [snowdrop-bot/snowdrop-bot#53]
At the moment the snowdrop bot is able to connect to JIRA.

We should definitely include JIRA issues in the report and also display them in the `Issues` tab. 
From there we should consider other integrations too (maybe a bridge similar to the one we use for 3rd part repositories).

**Comment by cmoulliard** [comment]
This project should help you to get the issues from different systems: https://github.com/jboss-set/aphrodite
