### ISSUE TITLE
Improve the Issue entity so it's more generic and supports more information

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop-bot/snowdrop-bot#55]
Aiming to have issues from different sources, and to generate the weekly report some improvements are identified to the Issue entity. For this we need to make the Issue entity more generic so it fits supporting more information from other sources such as Jira, also aiming to the CVE report.

Other fields could be:
  - [x] Source: [GITHUB, JIRA, ...]
  - [x] Affected version (from JIRA)
  - [x] Fix version (for JIRA, but also might include a milestone from github)
  - [x] Status
  - [x] Label
  - [x] Group

Moreover, move this entity to another package, independent from GitHub, such as `io.snowdrop.reporting.model`.

**Comment by iocanel** [comment]
We could keep the number as is and have the project name in the same field we currently have the `org/project` thing.
