### ISSUE TITLE
Implement reporting format in markdown / asciidoc

### ISSUE THREAD

**Issue by iocanel** [snowdrop-bot/snowdrop-bot#56]
Depends on #55 

At the moment the generated report is in google doc format.

We need to provide the option of exporting the report in markdown or asciidoc and commit the report to an external repository.

**Comment by cmoulliard** [comment]
Wait feedback from discussions that we will have with @jacobdotcosta before to develop something.

**Comment by jacobdotcosta** [comment]
I would start with having the markdown source code as plain text first then think about creating the GitHub issue.
