### ISSUE TITLE
Review the kohsuke GitHub API to check for improvements

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop-bot/snowdrop-bot#57]
Check the https://github-api.kohsuke.org/ GitHub API to see if we can get improvements regarding the currently used API.

**Comment by jacobdotcosta** [comment]
I've downloaded the kohsuke jar and I don't see discussion support in neither there nor in the github library we're current using (egit). I think if we're going to change the library we use to communicate with github we should try finding one that actually supports discussions.

WDYT @iocanel @cmoulliard?

**Comment by jacobdotcosta** [comment]
I've been checking for another library and found a list of them at [github libraries page](https://developer.github.com/v3/libraries/). For Java there's a 3rd one there called [JCabi](https://github.jcabi.com/). Unfortunately I don't see any discussion support there either.

**Comment by jacobdotcosta** [comment]
The APIv3 page for discussions is here... https://developer.github.com/v3/teams/discussions/

**Comment by cmoulliard** [comment]
I created a feature request - https://github.com/hub4j/github-api/issues/828

**Comment by jacobdotcosta** [comment]
As commented, since we have to change the library being used we might as well as migrate to the [aphroditte github project](https://github.com/jboss-set/aphrodite) and gain this way connection to other systems.

**Comment by jacobdotcosta** [comment]
Replaced by #85
