### ISSUE TITLE
Display associate name instead of github acronym

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop-bot/snowdrop-bot#71]
Display the associate name instead of showing the github acroynm.

**Comment by jacobdotcosta** [comment]
Since we should also merge JIRA issues into the associate's weekly report, we could have a table that would unify the JIRA and the GITHUB associate ID aswell as the name to be shown.

WDYT @iocanel @cmoulliard ?

**Comment by cmoulliard** [comment]
> Since we should also merge JIRA issues into the associate's weekly report, we could have a table that would unify the JIRA and the GITHUB associate ID aswell as the name to be shown.

+1
