### ISSUE TITLE
The issue collector should handle `bridged` issues.

### ISSUE THREAD

**Issue by iocanel** [snowdrop-bot/snowdrop-bot#73]
If we add a bridged organizaiton (e.g. `snowdrop-zen`) in the `github.reporting.organizations` list, then we will end up with dublicate issues.

To prevent that, we should be able to detect issues that are bridged and only insert in the database the upstream issue instead of the bridged issue.

Why?

Because, the upstream issue has more information than the downstream, is associated with pull requests etc. Bridged issues are mostly used for Zenhub like boards.

**Comment by jacobdotcosta** [comment]
The suggestion is to also include as additional repositories in the IssueCollector the values of the `github.bridge.source-repos` property and don't add the `snowdrop-zen`.
