### ISSUE TITLE
Adapt to dekorate in order to deploy on k8s

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop-bot/snowdrop-bot#78]
Adapt this project in order to have it published in k8s/ocp server.

**Comment by iocanel** [comment]
There is no need to adapt dekorate. Quarkus has its own extension (which is based on dekorate) that is used to generate manifests. We are already using it btw.

You will find the generated files under `target/kubernetes`.

**Comment by iocanel** [comment]
@jacobdotcosta ^^
